# deploys the serverless configuration
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - apt-get update
      - curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
      - bash nodesource_setup.sh
      - apt install nodejs
      - npm install -g serverless
      - sls deploy