service: Banners

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  stackName: ${self:service}
  logRetentionInDays: 14

package:
  individually: true

plugins:
  - serverless-step-functions

functions:
  trigger:
    handler: functions/trigger/src/handler.lambda_handler
    name: ${self:service}-trigger
    memorySize: 128
    package:
      exclude:
        - ./**
      include:
        - functions/trigger/src/**
    environment:
      stateMachineArn: arn:aws:states:{{ aws_region }}:{{ aws_caller_facts.account }}:stateMachine:Banners
    events:
      - s3:
        bucket: ClickstreamBucket
        events:
          - s3:ObjectCreated:Put
        rules:
          - prefix: in/

  deduplicate:
    handler: functions/deduplicate/src/handler.lambda_handler
    name: ${self:service}-deduplicate
    package:
      exclude:
        - ./**
      include:
        - functions/deduplicate/**
    environment:
      tableName: !Ref DynamoDBClicks

  aggregate:
    handler: functions/aggregate/src/handler.lambda_handler
    name: ${self:service}-aggregate
    package:
      exclude:
        - ./**
      include:
        - functions/aggregate/**

stepFunctions:
  stateMachines:
    BannersClickStream:
      name: BannersClickStream
      definition:
        StartAt: Deduplication
        States:
          Deduplication:
            Type: Task
            Resource: !GetAtt deduplicate.Arn
            Next: Aggregation
          Aggregation:
            Type: Task
            Resource: !GetAtt aggregate.Arn
            End: true

resources:
  Resources:
    ClickstreamBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

    DynamoDBClicks:
      Type: AWS::DynamoDB::Table
      Properties:
        # only define the attributes that DynamoDB needs to know about to build the KeySchema
        AttributeDefinitions:
          - AttributeName: click_id
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: click_id
            KeyType: HASH
